name: Blob storage website CI

on:
  push:
      branches: [ master ]
  pull_request:
      branches: [ master ]
  workflow_dispatch:

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Azure Login
          uses: azure/login@v1
          with:
              creds: ${{ secrets.AZURE_CREDENTIALS_RADIOPAGS }}    
        - name: Azure CLI script
          uses: azure/CLI@v1
          with:
              azcliversion: 2.31.0
              inlineScript: |
                  az storage blob upload-batch --account-name radiopags -d \$web -s . --subscription ${{ secrets.AZURE_ACCOUNT_WEBSITE_SUB }}

        - name: Azure CLI script
          uses: azure/CLI@v1
          with:
              azcliversion: 2.31.0
              inlineScript: |
                az cdn endpoint purge --content-paths  "/*" --profile-name "radiopags-cdn-profile" --name "radiopags" --resource-group "RadioPags"

        # Azure logout 
        - name: logout
          run: |
            az logout
